lang: "en-US"
start: "21:00"
duration: 15
enable_pvp: true
enable_chests: true
overwrite_safezone: false
num_start_warnings: 5
num_stop_warnings: 3
enabled_days:
  monday: true
  tuesday: true
  wednesday: true
  thursday: true
  friday: true
  saturday: true
  sunday: true