#     ____       _   _            _____
#    |  _ \     | | | |          |  __ \
#    | |_) | ___| |_| |_ ___ _ __| |__) |   _ _ __ __ _  ___
#    |  _ < / _ \ __| __/ _ \ '__|  ___/ | | | '__/ _` |/ _ \
#    | |_) |  __/ |_| ||  __/ |  | |   | |_| | | | (_| |  __/
#    |____/ \___|\__|\__\___|_|  |_|    \__,_|_|  \__, |\___|
#                                                  __/ |
#                                                 |___/
# BetterPurge V${project.version}

# start of the Purge
start : {start}

# duration of the purge
duration : {duration}






