#     ____       _   _            _____
#    |  _ \     | | | |          |  __ \
#    | |_) | ___| |_| |_ ___ _ __| |__) |   _ _ __ __ _  ___
#    |  _ < / _ \ __| __/ _ \ '__|  ___/ | | | '__/ _` |/ _ \
#    | |_) |  __/ |_| ||  __/ |  | |   | |_| | | | (_| |  __/
#    |____/ \___|\__|\__\___|_|  |_|    \__,_|_|  \__, |\___|
#                                                  __/ |
#                                                 |___/
# BetterPurge v${project.version}

#
# Purge start/end settings
#

# The starting time of the purge, in the format HH:MM
start : {start}

# The duration of the purge in minutes. Must lie in the range [2, 1400]
# Eg. the purge is active for one hour and 14 minutes: set this to 74
duration : {duration}

# Pick the days for which the purge will be enabled
# Set them to true to enable them, and false to not have a purge on this day
enabled_days:
  monday: {enabled_days.enabled}
  tuesday: {enabled_days.enabled}
  wednesday: {enabled_days.enabled}
  thursday: {enabled_days.enabled}
  friday: {enabled_days.enabled}
  saturday: {enabled_days.enabled}
  sunday: {enabled_days.enabled}

#
# Plundering settings
#

# Allow container access during the purge, this bypasses ALL chest protection plugins (this includes worldguard, chestshops, lockette, ...)
enable_chests: {enable_chests}

#
# PVP settings
#

# Whether to handle PVP
# When true:
#     - PVP outside of the purge is NOT allowed
#     - PVP during the purge IS allowed
# When false:
#
enable_pvp: {enable_pvp}

# Whether to allow pvp in otherwise non-pvp zones (created with plugins such as worldguard)
# When true:
#     - PVP is allowed everywhere, this includes spawn areas
overwrite_safezone: {overwrite_safezone}